version: '3.8'

services:
  user-postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  menu-postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  user-service:
    build: ./src/user-service
    environment:
      DB_URL: jdbc:postgresql://user-postgresql:5432/user_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8000:8000"
    depends_on:
      - user-postgresql
      - rabbitmq

  menu-service:
    build: ./src/menu-service
    environment:
      DB_URL: jdbc:postgresql://menu-postgresql:5432/menu_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8001:8001"
    depends_on:
      - menu-postgresql
      - rabbitmq