apiVersion: v2
name: online-cafe
description: Umbrella chart for Online Cafe Microservices
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: discovery-service
    version: 0.1.0
    repository: file://../discovery-service
    condition: discovery-service.enabled
  - name: user-service
    version: 0.1.0
    repository: file://../user-service
    condition: user-service.enabled
  - name: menu-service
    version: 0.1.0
    repository: file://../menu-service
    condition: menu-service.enabled
  - name: order-service
    version: 0.1.0
    repository: file://../order-service
    condition: order-service.enabled
  - name: payment-service
    version: 0.1.0
    repository: file://../payment-service
    condition: payment-service.enabled
  - name: api-gateway
    version: 0.1.0
    repository: file://../api-gateway
    condition: api-gateway.enabled
  - name: rabbitmq
    version: 12.6.2
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: postgresql
    version: 12.9.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled