apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-db-secret
type: Opaque
data:
  url: {{ .Values.database.url | b64enc }}
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}